language: node_js
node_js:
  - 12
  - "stable"
cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
install:
  - npm install
os: osx
osx_image: xcode10.1
script:
  - npm run release -- --mac --win
